application: sweet-polls
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /styles
  static_dir: dist/app/dev/styles

- url: /scripts
  static_dir: dist/app/dev/scripts

- url: /fonts
  static_dir: dist/app/dev/fonts

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^bower_components(/.*)?$
- ^client(/.*)?$
- ^node_modules(/.*)?$
