application: sweet-polls
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /profile_pics
  static_dir: profile_pics
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest